# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 046c816853202af0d51d66a2b826fadb0c84f993c15312d7e2ef3a1cc689f464bd17279ef54b0c9e14d92398e11a5fc34d5a5245b0fc3a19e97f19ebd9eb961c

test:
  secret_key_base: 07508363cf839b8ce4cc2be8de40b6b20e4eab92cb0891dfc9d157cc06bbbc69d01da809e05be5fd3eac461da306937fb3c64f7b411161d68ca113a26653ff34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
